export interface TokenAuth {
  token?: string | null;
  organization_name?: string | null;
  has_point_categories?: boolean | null;
  organization_details?: OrganizationDetail | null;
  user_details?: UserProfile | null;
  hide_leaderboard?: boolean | null;
  connected_tracker?: string | number | null;
  cerra_rewards?: boolean | null;
  require_twofa?: boolean | null;
  currency?: string | null;
  require_email_twofa?: boolean | null;
  organization_settings?: OrganizationSettings | null;
  date_for_point_credit?: string | number | null;
  layer_app_id?: string | number | null;
  has_discount_categories?: boolean | null;
  terms_and_conditions?: string | null;
  title?: string | null; // TnC title
  status?: number | null | string;
  redirect_url?: string | null;
  real_time_points?: number | null;
}

export interface Organization {
  pk?: number;
  name?: string;
  slug?: string | null;
  country?: string | null;
  logo?: string | null;
  background_color?: string | null;
  settings?: OrganizationSettings;
}

export interface OrganizationDetail {
  logo?: string | null;
  background_color?: string | null;
  slug?: string | null;
  emergency_services_available?: boolean | null;
  country?: string | null;
  ask_to_accept_terms_and_conditions?: number | null;
}

export interface OrganizationSettings {
  enable_special_deal_filter?: number | null;
  enable_ecards?: number | null;
  enable_facility_checkin?: number | null;
  user_weekly_report_subject?: string | null;
  proration_type?: number | null;
  enable_point_allocation_with_certificate?: number | null;
  supervisor_personal_points_allocation?: number | null;
  reward_tier_reset_date?: string | null;
  show_greetings?: number | null;
  organization_low_balance_threshold?: number | null;
  enable_activity_tracker?: number | null;
  include_sales_dashboard?: number | null;
  send_sms_from_org_phone_number?: number | null;
  cerra_rewards?: number | null;
  number_of_receipt_approval_required?: number | null;
  enable_benefit_receipts_upload?: number | null;
  enable_gamification?: number | null;
  nomination_auto_approve_for_same_level?: number | null;
  nearby_distance?: number | null;
  check_in_max_distance?: number | null;
  receipt_cut_off_day?: number | null;
  enable_registration_with_employee_id?: number | null;
  line_managers_cc_email_criteria?: string | null;
  enable_tier?: number | null;
  enable_feedback?: number | null;
  number_of_rewards?: number | null;
  number_of_chracters_for_appreciation_message?: number | null;
  permitted_days_for_benefit_recipt_upload?: number | null;
  use_custom_receipt_fields?: number | null;
  include_assign_customer_view?: number | null;
  send_email_from_org_name?: number | null;
  hide_leaderboard?: number | null;
  enable_decimal_support_in_transaction?: number | null;
  organization_low_awarding_balance_threshold?: number | null;
  hide_team_leaderboard?: number | null;
  enable_atsn?: number | null;
  set_link_redirection_url?: number | null;
  maximum_points_allowed_to_redeem_on_rewards?: number | null;
  flexi_benefits_url?: string | null;
  send_whatsapp_message_from_org_phone_number?: number | null;
  transaction_limit_per_appreciation_for_user?: number | null;
  enable_analytics?: number | null;
  date_for_point_credit?: number | null;
  benefit_points_deduct_on_receipt_upload?: number | null;
  allow_only_admin_to_post_feeds?: number | null;
  logout_users_for_inactivity_from_web?: number | null;
  enable_reward_history_dashboard?: number | null;
  weekly_news_day?: number | null;
  admin_charge?: number | null;
  receipt_points_splitting_ratio?: number | null;
  monthly_staff_appreciation_limit?: number | null;
  monthly_appreciation_limit?: number | null;
  enable_biometrics?: number | null;
  enable_receipts_upload?: number | null;
  hide_whats_on?: number | null;
  additional_receipt_fields?: number | null;
  rewards_points_multiplier?: number | null;
  ask_to_accept_terms_and_conditions?: number | null;
  points_calculation_based_on_active_section_round?: number | null;
  enable_password_change?: number | null;
  show_rewards_in_admin_functions?: number | null;
  daily_activity_points_cap?: number | null;
  send_credit_message_on_receipt_approval?: number | null;
  need_otp_on_external_link?: number | null;
  slack_channel_name?: number | null;
  monthly_appreciation_budget?: number | null;
  givz_campaign_id?: number | null;
  no_of_receipt_alert_units?: number | null;
  benefit_receipts_validity_days?: number | null;
  appreciation_limit_time_and_frequency?: number | null;
  enable_department_level_receipt_approval?: number | null;
  require_twofa?: number | null;
  show_quick_links?: number | null;
  enable_referral_page?: number | null;
  child_org_uses_parent_org_balance?: number | null;
  e_cash_multiplier?: number | null;
  organization_common_slug?: string | null;
  enable_rewards?: number | null;
  show_birthdays_in_greetings?: number | null;
  allow_one_appreciation_per_month?: number | null;
  send_email_from_org_email?: string | null;
  supervisor_point_allocation_date?: string | null;
  leaderboard_reset_points?: number | null;
  step_activity_limit?: number | null;
  benefit_selection_reminder_days?: number | null;
  redeem_with_real_money?: string | null;
  stop_redemption_when_low_balance?: number | null;
  show_greetings_from_affiliated_org?: number | null;
  enable_nominations?: number | null;
  recognition_heroes_from_affiliated_orgs?: number | null;
  appreciation_default_points?: number | null;
  send_credit_view?: number | null;
  fixed_appreciation_value?: number | null;
  send_user_activation_email?: number | null;
  require_approval_for_point_allocation_by_admin?: number | null;
  enable_news_feed?: number | null;
  p2p_points_limit?: number | null;
  charity_percentage?: number | null;
  multi_org_post?: number | null;
  points_expiry_frequency?: string | null;
  supervisor_budget_expiry_date?: number | null;
  disable_file_upload_in_ui?: number | null;
  nomination_auto_approve_for_different_hierarchy?: number | null;
  allow_affiliated_orgs?: number | null;
  hide_parent_org_from_appreciation_org_filter?: number | null;
  show_flexi_in_admin_dashboard?: number | null;
  benefit_selection_end_day_period?: string | null;
  award_points_on_successful_steps_challenge?: number | null;
  max_tier_level?: number | null;
  require_email_twofa?: number | null;
  enable_send_webhook_notification?: number | null;
  allow_send_both_voucher_credit?: number | null;
  show_events?: number | null;
  logout_users_for_inactivity_from_mobile?: number | null;
  show_departments_for_system_created_greetings?: number | null;
  enable_category_based_filter?: number | null;
  enable_new_receipt_flow?: number | null;
}

export interface User {
  pk?: number | null;
  email?: string | null;
  employee_id?: string | null;
  name?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  gender?: string | null;
  nationality?: string | null;
  phone_number?: string | null;
  date_of_birth?: string | null;
  wedding_date?: string | null;
  roles?: any[] | null;
  id_type?: string | null;
  id_number?: string | null;
  organization_pk?: number | null;
  organization_name?: string | null;
  departments_ids?: string[] | null;
  department_name?: string | null;
  departments_list?: string[] | null;
  groups_ids?: number[] | null;
  groups_list?: string[] | null;
  is_profile_public?: string | null;
  profile_pic_url?: string | null;

  // Flags
  is_active?: boolean | null;
}

export interface UserProfile {
  pk?: number | null;
  email?: string | null;
  phone_number?: string | null;
  organization_name?: string | null;
  organization_pk?: number | null;
  organization_logo?: string | null;
  department_name?: string | null;
  using_default_password?: boolean | null;
  profile_pic_url?: string | null;
  official_title?: string | null;
  real_title?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  office_phone_number?: string | null;
  address?: string | null;
  address2?: string | null;
  martial_status?: string | null;
  date_of_birth?: string | null;
  wedding_date?: string | null;
  is_staff?: boolean | null;
  mantra?: string | null;
  is_profile_public?: boolean | null;
  rank?: number | null;
  is_dob_public?: boolean | null;
  is_anniversary_public?: boolean | null;
  departments_list?: string[] | null;
  groups_list?: string[] | number[] | null;
  departments_ids?: string[] | null;
  groups_ids?: string[] | number[] | null;
  img?: string | number | null;
  employee_id?: string | null;
  is_p2p_staff?: boolean | null;
  appreciation_left?: string | number | null;
  current_tier?: string | null;
  hide_appreciation?: boolean | null;
  is_marketing_staff?: boolean | null;
  termination_date?: string | number | null;
  date_of_joining?: string | null;
  age?: number | null;
  is_send_low_balance?: boolean | null;
  is_send_affilated_org_low_balance?: boolean | null;
  is_admin_staff?: boolean | null;
  benefit_grade?: string | number | null;
  nationality?: string | null;
  id_type?: string | null;
  id_number?: string | null;
  base_salary?: string | number | null;
  is_department_receipt_approver?: boolean | null;
  no_of_dependents?: number | null;
  is_point_allocation_approver?: boolean | null;
  received_count?: number | null;
  given_count?: number | null;
  post_poll_count?: number | null;
  real_time_points?: number | null;
  checked?: boolean | null;
  line_manager?: {
    pk?: number | null;
    first_name?: string | null;
    last_name?: string | null;
    profile_pic_url?: string | null;
  } | null;
  departments?: Department[] | null;
  profile_img?: string | null;
  full_name?: string | null;
  tax_percentage?: string | null;
  is_line_manager?: boolean | null;
  is_first_time_login?: boolean;
  created?: string | null;
  website_url?: string;
  has_accepted_terms_and_cond?: boolean | null;
}

export interface Department {
  pk?: number | null;
  id?: number | null;
  name?: string | null;
  slug?: string | null;
  org_slug?: string | null;
  organization_name?: string | null;
}